### ISSUE TITLE
dsygu filter broken for non-translocations

### ISSUE THREAD

**Issue by kdm9** [kcleal/dysgu#100]
Hello,

I think some recent refactoring of filter_normal.py has broken `dysgu filter`. I suspect the cause is that [`process_intra()`](https://github.com/kcleal/dysgu/blob/eeafe830e2c07f91f4cc9fc0eb3ce8b72d16069d/dysgu/filter_normals.py#L888C5-L888C18) never returns None. From a brief inspection of `dysgu filter --keep-all` it seems to complain about low support for all non-TRA events. I tried to track the logic of `process_intra()` but ran out of time.

I've confirmed that version `1.6.2` works as expected, but nothing since then does, so I suspect the bug [is somewhere here](https://github.com/kcleal/dysgu/compare/v1.6.2...v1.6.3#diff-e3d818e59317d6aa6049a931b2f8d05b26a179c0fd8dfb8b12552178bb4c961c).

I've already made a PR for a bug that prevented using `--keep-all` since v1.6.2, #99. 

best,
K

**Comment by kcleal** [comment]
Hi @kdm9,
Thanks for raising this, I will get this fixed asap.

**Comment by kdm9** [comment]
many thanks @kcleal, I've reached out by email to provide these details.

**Comment by kcleal** [comment]
v1.6.6 has been released - I think the issue should be resolved, but let me know if it still exists.

**Comment by kdm9** [comment]
Just confirming that in our hands, `dysgu filter` is working again now
