### ISSUE TITLE
Information about running multiple bam files 

### ISSUE THREAD

**Issue by poddarharsh15** [kcleal/dysgu#105]
Hi @kcleal ,

I need some information regarding running multiple BAM files (around 10, and possibly up to 100 in the future). Is it possible to run them using a text file [like job array] with the locations provided inside it? If so, could you please guide me on how to set this up, or if there's a specific parameter in `dysgu` I need to address for it?
Thank you for your assistance.

**Comment by kcleal** [comment]
Hi @poddarharsh15,
Im a little confused about what you mean. If you have 10 separate samples, you need to run dysgu once for each sample, before filtering/merging etc.

**Comment by poddarharsh15** [comment]
I apologize for the confusion. What I meant to ask is how to specify an input file to run Dysgu on several samples. 
What I understood from your reply, it appears that I need to run Dysgu for each sample separately and then analyze the results afterward. Is that correct?

**Comment by kcleal** [comment]
Yes that is correct
