### ISSUE TITLE
Probably pysam error 

### ISSUE THREAD

**Issue by poddarharsh15** [kcleal/dysgu#107]
Hi @kcleal,

I hope you're doing well. I'm encountering some errors while using the latest version of Dysgu within a Conda environment. I have attached the log.txt file for your reference. Could you please take a look when you have a moment?

Thank you in advance for your help!

> command used 

`dysgu run -x -p 16 --min-support 5 --mq 5 GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta  $temp1  UD_AN001_F.sorted.uniq.bam --regions $exones_padded_50bp_sorted.bed | bgzip -c > dysgu_output.vcf.gz`

[log.txt](https://github.com/user-attachments/files/16964364/log.txt)
[process_bams_dysgu_732982_1.txt](https://github.com/user-attachments/files/16964454/process_bams_dysgu_732982_1.txt)

**Comment by kcleal** [comment]
Hi @poddarharsh15,

It looks like the posA and posB coordinates are the wrong way around. This should be straight forward to fix. Thanks for raising the issue

**Comment by poddarharsh15** [comment]
Thanks for the fast response :)

**Comment by poddarharsh15** [comment]
> Hi @poddarharsh15,
> 
> It looks like the posA and posB coordinates are the wrong way around. This should be straight forward to fix. Thanks for raising the issue

Hi @kcleal,
I wanted to follow up and ask if the issue has been resolved, as I'm still a bit unclear on the current status. Could you please provide an update when you have a moment?
Thank you very much for your help.

**Comment by poddarharsh15** [comment]
great thanks for clarifying I will run some test with newer version :)

**Comment by poddarharsh15** [comment]
Hi @kcleal,
Thank you again for the update. I wanted to share two scenarios I’ve tested with the same sample set. Please see the details below:

Using the `--regions` parameter to exclude certain regions in my WES data
I ran test samples using the --regions parameter to exclude specific exons, but unfortunately, I am still encountering the same errors. Please refer to the attached log files for detailed error descriptions. I am not 100% sure but I think there is some problem with .bed files I am using with my WES data and I think I can ignore the regions parameters. 
[with_region_param.txt](https://github.com/user-attachments/files/16994824/with_region_param.txt)


Without including the `--regions` parameter
When I omit the --regions parameter, the pipeline runs successfully and completes without any errors.
[no_regions.txt](https://github.com/user-attachments/files/16994826/no_regions.txt)


Conda installs a new version of dysgu, but shows version 1.6.6
Even though I installed the latest version of dysgu via Conda, it still reports version 1.6.6 when checked.
![Screenshot from 2024-09-13 12-49-40](https://github.com/user-attachments/assets/53d509ed-7f30-4472-959a-fe830b758c7c)

![Screenshot from 2024-09-13 12-50-22](https://github.com/user-attachments/assets/30d24d70-40e7-4dba-ad9a-dde74743e1e0)


Please let me know if you have any suggestions or insights into these issues.

Many thanks again for your help.

**Comment by kcleal** [comment]
Oh that's unexpected. Sometimes if you install via pip, then install using conda, the pip version still gets used. Perhaps this is the reason? You might need to run pip uninstall dysgu a few times.

**Comment by poddarharsh15** [comment]
Hi @kcleal,
I’ve tried several times to uninstall (through pip) the old version of dysgu and reinstall it using Conda. Unfortunately, I still end up with version 1.6.6 after the installation.
However, I have decided not to use the --regions parameter anymore, as I do not have accurate BED files for the regions I intended to exclude.

Many thanks again for your help!

**Comment by kcleal** [comment]
Ok no problem. Sorry, I dont know why you are seeing v1.6.6, I seem to have no issues downloading 1.6.7
