### ISSUE TITLE
Issues when installing with `conda`

### ISSUE THREAD

**Issue by jsquaredosquared** [kcleal/dysgu#109]
In the readme, the suggested installation command is `conda install -c bioconda -c conda-forge dysgu`. However, this causes a `LibMambaUnsatisfiableError` due to incompatible packages. 

Changing the command to `conda install -c conda-forge -c bioconda dysgu` solves this problem. This is because the conda-forge channel needs to have a higher priority because "bioconda heavily depends on the conda-forge channel" ([source](https://bioconda.github.io/#explain-commands)). Perhaps the readme should be updated to use this command instead?

Furthermore, I encountered an issue where running `conda install -c conda-forge -c bioconda dysgu` would install Dysgu successfully along with the latest version of NumPy, but then when running `dysgu run` it would throw the following error:

```
pkg_resources.ContextualVersionConflict: (numpy 2.1.1 (/[...]/lib/python3.12/site-packages), Requirement.parse('numpy<2'), {'dysgu'})
```

Perhaps the requirements need to be updated?

**Comment by kcleal** [comment]
Hi @jsquaredosquared,
Thanks for pointing this out, I will get the docs updated. You right there is a mismatch in the numpy versions between conda package and the python package, I will have to fix those.
