### ISSUE TITLE
small duplication false negative

### ISSUE THREAD

**Issue by husamia** [kcleal/dysgu#14]
Why does dysgu-SV not detect this 77bp duplication? the reads look pretty good. It's a custom library target NGS with illumina with high coverage. I tried the option --keep-small and still didn't call it. Is this by design or false negative or what?

![image](https://user-images.githubusercontent.com/13439952/134205643-61989e4c-8aa3-4d3c-9a37-07af84efc9b7.png)

**Comment by kcleal** [comment]
Hi Husamia,
If you could show the full command that you used to run dysgu I might have some futrther ideas. But my first though was that the `--max-cov` parameter of dysgu might not be set properly. The coverage in the region looks very high, so dysgu is probably ignoring it if the default setting is used

**Comment by kcleal** [comment]
Setting it to a very high number e.g. 100000 will hopefully resolve this. In the next release I will add an option to use `--max-cov -1` to turn off filtering by coverage

**Comment by husamia** [comment]
I will test it and report back

**Comment by husamia** [comment]
Command
`dysgu run -o XXX_dysgu.vcf --mode pe --max-cov 100000 /mnt/e/human_g1k_v37.fasta /mnt/e/XXX/dysgu /mnt/e/EB-dysgu/XXX.dedup.rg.recal.bam`

Output
`2021-09-28 11:39:37,370 [INFO   ]  [dysgu-run] Version: 1.1.7
2021-09-28 11:39:37,372 [INFO   ]  run -o XXX_dysgu.vcf --mode pe --max-cov 100000 /mnt/e/human_g1k_v37.fasta /mnt/e/EB-dysgu/dysgu /mnt/e/EB-dysgu/XXX.dedup.rg.recal.bam
2021-09-28 11:39:37,372 [INFO   ]  Destination: /mnt/e/EB-dysgu/dysgu
2021-09-28 11:42:13,242 [INFO   ]  dysgu fetch /mnt/e/EB-dysgu/XXX.dedup.rg.recal.bam written to /mnt/e/EB-dysgu/dysgu/XXX.dedup.rg.recal.dysgu_reads.bam, n=2903389, time=0:02:35 h:m:s
2021-09-28 11:42:13,242 [INFO   ]  Input file is: /mnt/e/EB-dysgu/dysgu/XXX.dedup.rg.recal.dysgu_reads.bam
[E::idx_find_and_load] Could not retrieve index file for '/mnt/e/EB-dysgu/dysgu/XXX.dedup.rg.recal.dysgu_reads.bam'
2021-09-28 11:42:13,254 [INFO   ]  Input file has index False
2021-09-28 11:42:13,547 [INFO   ]  Sample name: XXX
2021-09-28 11:42:13,547 [INFO   ]  Writing SVs to XXX_dysgu.vcf
2021-09-28 11:42:13,549 [INFO   ]  Running pipeline
2021-09-28 11:42:15,055 [INFO   ]  Removed 70 outliers with insert size >= 659.0
2021-09-28 11:42:15,071 [INFO   ]  Inferred read length 151.0, insert median 187, insert stdev 82
2021-09-28 11:42:15,071 [INFO   ]  Max clustering dist 597
2021-09-28 11:42:15,071 [INFO   ]  Minimum support 3
2021-09-28 11:42:15,072 [INFO   ]  Building graph with clustering distance 597 bp, scope length 597 bp
2021-09-28 11:43:24,881 [INFO   ]  Total input reads 2903389
2021-09-28 11:43:25,257 [INFO   ]  Graph constructed
2021-09-28 12:03:35,405 [INFO   ]  Number of components 1361392. N candidates 33977
2021-09-28 12:03:59,325 [INFO   ]  Re-alignment of soft-clips done. N candidates 8206
2021-09-28 12:03:59,721 [INFO   ]  Number of candidate SVs merged: 2545
2021-09-28 12:03:59,722 [INFO   ]  Number of candidate SVs after merge: 5661
2021-09-28 12:03:59,723 [INFO   ]  Number of candidate SVs dropped with sv-len < min-size or support < min support: 2835
2021-09-28 12:04:00,279 [INFO   ]  N near gaps dropped 272
2021-09-28 12:04:04,952 [INFO   ]  Loaded n=81 chromosome coverage arrays from /mnt/e/EB-dysgu/dysgu
2021-09-28 12:04:06,095 [INFO   ]  Adding genotype
/home/husamia/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.23.2 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
2021-09-28 12:04:08,160 [INFO   ]  Model: pe, diploid: True, contig features: True. N features: 41
2021-09-28 12:04:09,165 [INFO   ]  dysgu call /mnt/e/EB-dysgu/dysgu/XXXX.dedup.rg.recal.dysgu_reads.bam complete, n=2554, time=0:21:55 h:m:s
2021-09-28 12:04:09,182 [INFO   ]  dysgu run /mnt/e/EB-dysgu/XXXX.dedup.rg.recal.bam complete, time=0:24:31 h:m:s`


it detected as INS

`1	209803179	112	N	<INS>	.	PASS	SVMETHOD=DYSGUv1.1.7;SVTYPE=INS;END=209803256;CHR2=1;GRP=4051;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;SVLEN=48;CONTIGA=tggtccgatcaattgtcacacacacctccatatgccccctggctggcggcaaacacagcggggtcaaagtgacatgtctctgagtgcccTTGTCACACACACCTCCATATGCCCCCTGGCTGGCGGCAAACACAGCGGGGTCAAAGTGACATGTCTCTGAGTGCCCATTGCAGTCGCACCCTGGAAAAAGAGAGTCCCAGGGCTGACATCTGACCCACACCTTTGCTATCTACAGAG;CONTIGB=TCCGGAAATAGTGCAGCTGACACCGCTCACAGTTCTTGCCTTCGGTGTGGTCCCGGCAATTGTCACACACACCTCCATATGCCCCCTGGCTGGCGGCAAACACAGCGGGGTCAAAGTGACATGTCTCTGAGTGCCCttgtcacacacacctccatatgccccctggctggcggcaaacacagcggggtcaaagtgacatgtctctgagtgcc;KIND=extra-regional;GC=57.02;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=246;WR=0;PE=235;SR=0;SC=470;BND=0;LPREC=1;RT=pe	GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB	0/1:200:60.0:246:0:235:0:470:0:669.43:47:235:235:0:0:211:0.001:14.104:0.021:0.587`

**Comment by husamia** [comment]
I think that it's calling every exon as an SV even thought it's not an SV. This is a custom panel where only the exon regions are enriched. Very different from whole genome sequencing. 

![image](https://user-images.githubusercontent.com/13439952/135129264-91c7030a-d71d-4026-a09c-3b0ec97da718.png)

**Comment by kcleal** [comment]
For targeted sequencing with high coverage, sometimes over clustering can occur, which might explain the false-positives you are seeing. There are a few options that should help, firstly I recommend you supply a .bed file listing the capture panel regions, this is supplied with the `--regions` option. Additionally, to prevent over clustering in high depth regions, you can set the `--regions-mm-only` flag; this will turn off clustering using discordant read pairs, and rely on minimizer clustering only.

**Comment by kcleal** [comment]
Hi husamia,
Did you make any progress on calling this small duplication? If you have time, would you be interested in trying the latest version of dysgu on this again?

**Comment by husamia** [comment]
Do you recommend default settings? I will give it a try.

**Comment by kcleal** [comment]
I recall you were using capture/WES data with quite high coverage?

If you have a bed file with individual exons available, this can be handed to dysgu using the ‘—regions’ option

A command might look like:

dysgu run —max-cov -1 —regions regions.bed —regions-only True $ref temp_dir sample.bam > output.vcf


In the output look for the KIND column in INFO. Events with  “KIND=intra-regional” will be SV events contained within a single exon region. SV events that have “KIND=inter-regional” are events that span different regions, so could be neighbouring exons for example.

Thanks,

Kez

On 30 Dec 2021, at 12:11, husamia ***@***.******@***.***>> wrote:

External email to Cardiff University - Take care when replying/opening attachments or links.
Nid ebost mewnol o Brifysgol Caerdydd yw hwn - Cymerwch ofal wrth ateb/agor atodiadau neu ddolenni.



Do you recommend default settings? I will give it a try.

> On Dec 23, 2021, at 2:51 PM, Kez Cleal ***@***.***> wrote:
>
> ﻿
> Hi husamia,
> Did you make any progress on calling this small duplication? If you have time, would you be interested in trying the latest version of dysgu on this again?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkcleal%2Fdysgu%2Fissues%2F14%23issuecomment-1003002463&data=04%7C01%7Cclealk%40cardiff.ac.uk%7C372ae16a30b54302973908d9cb8d7a27%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C637764630761007529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bHxE85iMkZb1aEl4EPvyArEd3v7wtTlVVixBOS5RTU8%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKIBQHM3LGICZTFJ6ZXECILUTRD6DANCNFSM5EO23OLQ&data=04%7C01%7Cclealk%40cardiff.ac.uk%7C372ae16a30b54302973908d9cb8d7a27%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C637764630761007529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cTB5A0KZD6U9moUYIZQOoZVPMdVCLhr%2FGP5iubBCk5E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cclealk%40cardiff.ac.uk%7C372ae16a30b54302973908d9cb8d7a27%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C637764630761007529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gU3LVClysSGzxmW6TYo1toFi3tu0fMwnxrHZEVAEios%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cclealk%40cardiff.ac.uk%7C372ae16a30b54302973908d9cb8d7a27%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C637764630761007529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dRxmP1PrvH6d9Oe1%2B6fj%2B%2F9kc%2BDbfw4lH3A6Z7mumZ4%3D&reserved=0>.
