### ISSUE TITLE
joint sample VCF

### ISSUE THREAD

**Issue by joonan30** [kcleal/dysgu#2]
Hi,

Thanks for the nice tool. Do you have some method (or future plan) for joint calling? 
I tried `merge` to combine multiple samples' VCFs but am not sure whether this is a correct way to get reference homozygous genotypes..

**Comment by brentp** [comment]
I have a similar question. Is there a genotype option? To re-genotype all samples on the merged VCF? This is critical for larger cohorts.

**Comment by kcleal** [comment]
Thanks for the suggestion, I agree this should be implemented. As suggested by @brentp, I think the option to re-genotype from an input vcf (from previous dysgu run or other SV caller) would be nice. I will try and get this implemented in the near future

**Comment by kcleal** [comment]
FYI, dysgu now has a --sites option that can be used to genotype a list of candidate sites. Thanks for the suggestion.
