### ISSUE TITLE
Location on CHR2 for translocations

### ISSUE THREAD

**Issue by tbenavi1** [kcleal/dysgu#20]
Hello, 

Thanks for your tool. I was wondering if there is any way for translocations to get the location on both chromosomes. At the moment I don't see this information in the VCF file (only CHR2). Thank you. 

P.S. I think the VCF format would encode these with SVTYPE=BND for each breakend. For my case I don't need the breakend information, but it would be great to get the location.

**Comment by kcleal** [comment]
Hi,
There should be an `END` column in the `INFO` field, in the example below `END=119401195`:

`1	119401194	623	C	<TRA>	.	PASS	SVMETHOD=DYSGUv1.3.5;SVTYPE=TRA;END=119401195;CHR2=2;GRP=11456;NGRP=1;CT=3to3;CIPOS95=0;CIEND95=0;CONTIGA=CTAGATGACACGTTAGTGGGTGCAGCGCACCAGCATGGCACATGTATACATATGTAACTAACCTGCACAATGTGCACATGTACCCTAAAGCTTAGAGTATAATAAAAAAAAAAAatTAAAAAAAAAAAAAATGATACATGTATACAATGTGGTATGATTAAATTAGGCTAATTAACATATCCTTCGCCTCACATACTTATCATTACGTTGTAATATATTTTCATATTGGGTAAAATTAAATGTATTACTAAATTGACTTATTCTTTTTTTACTTTTTTAATGCAGCTATTAAAATATTTAAGATCAaaaaaaaaaaaaaataaaaaaaaaaaaaaaaaaa;KIND=extra-regional;GC=25.29;NEXP=32;STRIDE=1;EXPSEQ=aaaaaaaaaaaaaataaaaaaaaaaaaaaaaa;RPOLY=50;OL=0;SU=87;WR=0;PE=87;SR=0;SC=41;BND=0;LPREC=1;RT=pe	GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB	1/1:200:58.14:87:0:87:0:41:0:2.13:0:142:32:0:0:332:0.0:0.75:0.5:0.547`

Not sure if that answers your question.

**Comment by kcleal** [comment]
There is now an extra column in the INFO field called `CHR2_POS`. I will upload a release to pypi over the weekend. Thanks again for raising this.
