### ISSUE TITLE
Does the merge command work for translocations?

### ISSUE THREAD

**Issue by tbenavi1** [kcleal/dysgu#22]
Apologies if I missed this somewhere, but does the merge command work for merging translocations across input samples? I used the merge command and it didn't seem to merge any, though I could be missing something. If it does merge translocations, is there information for how it does so? Thanks for any assistance.

**Comment by kcleal** [comment]
Hi. What version are you running? I think there was a bug in v1.3.4 that prevented merging of translocations. Hopefully v1.3.5 should fix things

**Comment by kcleal** [comment]
Closing this for now as I think it should be fixed

**Comment by tbenavi1** [comment]
Hello, as of version 1.3.9 I do not believe the merging is fixed for translocations. For example, I get the following lines (first 8 columns) in my merged vcf file:

2L      54217   467217  G       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54218;CHR2=2R;CHR2_POS=716508;GRP=11060;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=4;WR=0;PE=4;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.129;MaxPROB=0.129
2L      54231   567511  T       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54232;CHR2=2R;CHR2_POS=716509;GRP=199545;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=5;WR=0;PE=5;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.125;MaxPROB=0.125
2L      54240   978912  T       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54241;CHR2=2R;CHR2_POS=716509;GRP=74302;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=4;WR=0;PE=4;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.135;MaxPROB=0.135
2L      54240   365308  T       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54241;CHR2=2R;CHR2_POS=716522;GRP=66880;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=3;WR=0;PE=3;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.12;MaxPROB=0.12
2L      54244   735714  C       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54245;CHR2=2R;CHR2_POS=716515;GRP=154395;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=21;WR=0;PE=21;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.185;MaxPROB=0.185
2L      54255   1066664 A       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54256;CHR2=2R;CHR2_POS=716515;GRP=75082;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=11;WR=0;PE=11;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.134;MaxPROB=0.134
2L      54279   838209  T       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54280;CHR2=2R;CHR2_POS=716508;GRP=220145;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=5;WR=0;PE=5;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.101;MaxPROB=0.101
2L      54365   707335  A       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54366;CHR2=2R;CHR2_POS=716512;GRP=137288;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=6;WR=0;PE=6;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.133;MaxPROB=0.133
2L      54791   19056   C       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54792;CHR2=2R;CHR2_POS=716519;GRP=97622;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=7;WR=0;PE=7;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.153;MaxPROB=0.153
2L      54830   86198   A       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54831;CHR2=2R;CHR2_POS=716552;GRP=90866;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=4;WR=0;PE=4;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.084;MaxPROB=0.084
2L      54839   37783   A       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54840;CHR2=2R;CHR2_POS=716518;GRP=38716;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=6;WR=0;PE=6;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.136;MaxPROB=0.136
2L      54864   145869  G       <TRA>   .       lowProb SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54865;CHR2=2R;CHR2_POS=716522;GRP=114336;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=4;WR=0;PE=4;SR=0;SC=0;BND=0;LPREC=1;RT=pe;MeanPROB=0.11;MaxPROB=0.11

I believe they should all be merged as a single translocation. I ran dysgu merge with "--merge-dist 1000". Thanks for any help.

**Comment by kcleal** [comment]
Hi @tbenavi1,
Sorry I thought I had fixed this issue. I will take a look now

**Comment by kcleal** [comment]
Would you be able to send me the FORMAT column of these records (last column in the vcf file)? Thanks!

**Comment by kcleal** [comment]
Ive uploaded a patch which I think resolves the issue, however you will have to build from source until the patch is released to pypi for `pip install dysgu`.

Also I think the option `--merge-within True` might help when using the merge command - this performs an extra round of merging at the sample level before merging between samples. It can help increase the degree of merging 

I managed to recreate the problem from the data you sent (the dummy vcf file is attached as a zip):

Running `dysgu merge --merge-within True issue22.vcf issue22.vcf` resulted in two vcf records in the output:

`2L	54217	2	G	<TRA>	.	lowProb	SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54218;CHR2=2R;CHR2_POS=716508;GRP=11060;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=8;WR=0;PE=0;SR=0;SC=8;BND=8;LPREC=1;RT=pe;MeanPROB=0.657;MaxPROB=0.657	GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB	1/1:14:42.75:4:0:0:0:4:4:7.84:5:1:3:83:11:9:0.086:2.92:0.25:0.657	1/1:14:42.75:4:0:0:0:4:4:7.84:5:1:3:83:11:9:0.086:2.92:0.25:0.657
2L	54791	3	C	<TRA>	.	lowProb	SVMETHOD=DYSGUv1.3.9;SVTYPE=TRA;END=54792;CHR2=2R;CHR2_POS=716519;GRP=97622;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;GC=0.0;NEXP=0;STRIDE=0;EXPSEQ=;RPOLY=0;OL=0;SU=8;WR=0;PE=0;SR=0;SC=8;BND=8;LPREC=1;RT=pe;MeanPROB=0.657;MaxPROB=0.657	GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB	1/1:14:42.75:4:0:0:0:4:4:7.84:5:1:3:83:11:9:0.086:2.92:0.25:0.657	1/1:14:42.75:4:0:0:0:4:4:7.84:5:1:3:83:11:9:0.086:2.92:0.25:0.657`
[issue22.vcf.zip](https://github.com/kcleal/dysgu/files/8488435/issue22.vcf.zip)

**Comment by tbenavi1** [comment]
Thank you so much! I'll wait to double check once the patch is released to pypi. Feel free to close the issue for now. I can reopen if I still find an issue.

**Comment by kcleal** [comment]
v1.3.10 is now on pypi, hopefully that should resolve the issue. Closing this for now
