### ISSUE TITLE
Pickle Warning in run command

### ISSUE THREAD

**Issue by nickhsmith** [kcleal/dysgu#23]
Towards the end of the SV run command I noticed the following line:
`python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.23.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to: https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations  UserWarning`

Are you all aware of this? Should I be concerned about the `unpickle`?

Thanks in advance. Very easy to use tool btw.

**Comment by kcleal** [comment]
Thanks. I think this can safely be ignored, although I will leave this warning in for now
