### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by colindaven** [kcleal/dysgu#24]
Just a note for others.

Running manual installation (without conda) worked for me, but only after a little mucking around.

`conda deactivate
`

Then from the github README
```
git clone --recursive https://github.com/kcleal/dysgu.git
cd dysgu/dysgu/htslib
make
cd ../../
pip install --user -r requirements.txt
pip install .

```

```
Successfully installed dysgu-1.3.6


$ dysgu

Traceback (most recent call last):
  File "/home/rcug/.local/bin/dysgu", line 5, in <module>
    from dysgu.main import cli
  File "/home/rcug/.local/lib/python3.8/site-packages/dysgu/main.py", line 106, in <module>
    version = pkg_resources.require("dysgu")[0].version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/lib/python3/dist-packages), Requirement.parse('click>=8.0.0'), {'black'})

```

solved with

`pip install --user click==8.0`

Now works

```
Usage: dysgu [OPTIONS] COMMAND [ARGS]...

  Dysgu-SV is a set of tools calling structural variants from bam/cram files

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  call   Call structural variants from alignment file/stdin
  fetch  Filters input .bam/.cram for read-pairs that are discordant or...
  merge  Merge .vcf/csv variant files
  run    Run the dysgu pipeline.
  test   Run dysgu tests

```

**Comment by kcleal** [comment]
Thanks for posting this, I will add click>=8.0 to requirements. Are you using a Mac by any chance?

**Comment by colindaven** [comment]
Nope, Ubuntu linux 20.04

**Comment by Bingbing19** [comment]
Hi, 
Thanks for the post. I tried it without Conda and `pip install --user click==8.0` but see new error
`File "/opt/anaconda3/bin/dysgu", line 5, in <module>`
`from dysgu.main import cli`
`File "/opt/anaconda3/lib/python3.8/site-packages/dysgu/main.py", line 11, in <module>`
`from dysgu import cluster, view, sv2bam`
`ImportError: dlopen(/opt/anaconda3/lib/python3.8/site-packages/dysgu/cluster.cpython-38-darwin.so, 2): Library not loaded: /usr/local/lib/libhts.3.dylib`
`Referenced from: `/opt/anaconda3/lib/python3.8/site-packages/dysgu/cluster.cpython-38-darwin.so`
`Reason: image not found`
