### ISSUE TITLE
Reporting only SVs from --sites for genotyping

### ISSUE THREAD

**Issue by wbooker** [kcleal/dysgu#26]
Hi,

I'm interested in seeing how dysgu performs in genotyping a set of SVs discovered from a consensus of SV callers, but when running with --sites <vcf> and --all-sites True the output includes new SVs discovered by dysgu. Is there a way to report only the sites from the provided vcf? 

Thanks,
Will

**Comment by kcleal** [comment]
Hi Will,
There currently isn't a way to do this directly although I can see how this would be useful as a feature. I could have a look at implementing this, but there might be some issues getting this to work as expected.
In the mean time, you could try merging your reference set and dysgu SVs using a third party software e.g. jasmine https://github.com/mkirsche/Jasmine. Alternatively, if you only want to analyse the intersection without merging, svbench https://github.com/kcleal/svbench can be used for this

**Comment by wbooker** [comment]
Yeah I can see now how it is implemented why that might be difficult. For instance, it seems like if there is support for an SV at a provided site it might also change its position slightly, presumably the position as best supported by dysgu. I was considering just pulling out the SVs from the input vcf for each individual but since the positions don't necessarily overlap this would be tough.

At any rate, it seems like a great tool and I'm excited to see how it does on discovery for my samples more generally. And thanks for getting back to me so quickly!

**Comment by kcleal** [comment]
Yea, that is the problem exactly - the input sites only have a certain amount of influence over the final output SVs. In the current implementation input sites are assumed to have some level of error in them, so forcing the SV to match the input site is generally not a good idea. I might be able to add another way of providing a 'trusted' set of input sites which will then force a call to match an input site exactly. 
I will close this for now, but will put this on the list of things to add.
