### ISSUE TITLE
PacBio long reads?

### ISSUE THREAD

**Issue by beantkapoor786** [kcleal/dysgu#27]
Hello, thank you for creating this great software. I look forward to using this software in my analyses.

However, I have a question, does Dysgu supports PacBio long reads? I know you mention it supports PacBio HiFi reads but I was wondering about the PacBio long reads. Thank you, in advance. And I apologize if I missed this information.

**Comment by kcleal** [comment]
Hi,
There currently is no model for PacBio CLR, although I plan to add one. For now, using nanopore model would probably work best. I will leave this open until I add an additional model.

**Comment by beantkapoor786** [comment]
Great, thank you for your quick response!

**Comment by kcleal** [comment]
Unfortunately, I will not have time to add a model for CLR, and the technology is moving on too quickly to warrant it. Closing this for now.
