### ISSUE TITLE
Dysgu Cluster

### ISSUE THREAD

**Issue by assane-mbodj** [kcleal/dysgu#28]
Hi,
Thanks your for this tools.
I have a question. can dysgu run on a cluster. I would install this on the cluster.
Thanks your

**Comment by kcleal** [comment]
Hi,
Yes, although dysgu was really designed to work on a single node on a cluster.
Kez

**Comment by assane-mbodj** [comment]
I installed on the cluster but when i run my script; I have this error:

/var/spool/pbs/mom_priv/jobs/4418.master0.SC: line 65: /usr/local/bin/dysgu: No such file or directory

**Comment by kcleal** [comment]
Sometimes installation issues can arise if you try and use the system wide python on a cluster. One approach is to create a virtual environment. Alternatively, you can try installing Anaconda, and use the bundled python. Alternatively, if you have access to docker you can try that installation method. Hope that helps
