### ISSUE TITLE
PacBio CLR reads failing with Nanopore setting

### ISSUE THREAD

**Issue by AQWixom** [kcleal/dysgu#35]
Based on another issue posted here, I am running Dysgu with PacBio CLR reads using the Nanopore model. The specific error that it is outputting is:

Exception ignored in: 'dysgu.assembler.topo_sort2'
ValueError: Graph contains a cycle. Please report this. n=10, w=10, v=0. Node info n was: 10, 0, 0, 32
ValueError: Graph contains a cycle. Please report this. n=22, w=22, v=0. Node info n was: 6, 1, 0, 32

This occurs thousands and thousands of times using both the run and call subcommands. 

Any suggestions?

**Comment by kcleal** [comment]
Hi @AQWixom,

Thanks for reporting this. What was the mapper and reference genome you used?

You can bypass the error by setting the option `contigs False`, although the accuracy might be slightly lower.

**Comment by AQWixom** [comment]
Hi @kcleal 

I used pbmm2 and hg38.  

I will give that a shot and see if it will finish running through. Thanks!

**Comment by kcleal** [comment]
I think v1.3.10 should now work properly with pbmm2 - there were some issues with X/= style cigar strings that pbmm2 uses. Closing this for now, but please re-open if the issue persists!

**Comment by AQWixom** [comment]
The previous version did finish going through. I have updated to the newest version (side note: may want to include a numpy version in the requirements.txt, the numpy version that worked previously does not work with 1.3.10 and running the pip numpy install command when its already installed doesn't update it). I will let you know if there are problems. Thanks!
