### ISSUE TITLE
input vcf cannot be read

### ISSUE THREAD

**Issue by nponts** [kcleal/dysgu#38]
Hi,
And thanks for such a useful tool.
I'm exploring polymorphisms including previous data (in addition to new ones) and I'm trying to feed a VCF with --sites to dysgu run (conda env with python 3.9). I get the following error:
File "/opt/miniconda3/envs/dysgu/lib/python3.9/site-packages/dysgu/sites_utils.py", line 70, in vcf_reader
    svt = r.info["SVTYPE"]
  File "pysam/libcbcf.pyx", line 2581, in pysam.libcbcf.VariantRecordInfo.__getitem__
KeyError: 'Unknown INFO field: SVTYPE'
The VCF is v4.2 generated with bcftools 1.13
What can I do to fix the problem?
Thanks!

NP

**Comment by kcleal** [comment]
Hi @nponts 
As the error message indicates, the records in the vcf need to be labeled with SVTYPE, which is expected to be in the INFO column. This should have the same svtype naming convension as dysgu, so variants should be labelled as one of `SVTYPE=DEL`, `INS`, `INV`, `DUP`, `TRA`. If they have other names such as `INDEL`, or `INV:DUP`, for example, this can also cause problems. If some of the records are missing the `SVTYPE` label, then it will cause problems, so you should filter those out before passing to dysgu. If your records are missing the required labels, it is possible to add them in with a bit of work. I can recommend using the pyvcf3 library in python https://github.com/dridk/PyVCF3 - it is quite flexible for adding data to a vcf.

**Comment by nponts** [comment]
Hi, and thank you. I'll take a look at it and see how to work it out. Not so easy those things...
