### ISSUE TITLE
changing default argument when high read depth

### ISSUE THREAD

**Issue by splaisan** [kcleal/dysgu#40]
Hi
I am using a high coverage depth pacbio hifi dataset with depth 300+
I noticed that the default `--mode pacbio` includes `--max-cov 150` which is less than my actual avg data depth

```
pacbio: 
  --mq 20 
  --paired False 
  --min-support 2 
  --max-cov 150 
  --dist-norm 200 
  --trust-ins-len True
```

Can I add `--max-cov 500` after `--mode pacbio` and overwrite that parameter at runtime or should I set manually all arguments behind `--mode pacbio` and replace it altogether?

`dysgu run -p 24 --mode pacbio --max-cov 500 -x -c --thresholds 0.45,0.45,0.45,0.45,0.45 Sc.R64-1-1.fa wd mappings.bam > var.vcf`

Another point; what other values than 0.45 would one want to use for `--thresholds` and what would that mean?

thanks for your help

**Comment by splaisan** [comment]
also a suggestion for future version, include the full command in the VCF header for better tracing of our results

**Comment by kcleal** [comment]
Thanks for the suggestion, I will get that included.

You can set --mode pacbio and --max-cov 500 and it should work as expected. Alternatively you can use `--max-cov auto` which will give a max coverage of ~6x mean genome coverage (this will only really work for whole genome samples though)
For the thresholds, these are rather data set dependent, lower values will give higher sensitivity at the expense of precision. 0.45 seems to work for pacbio data in the coverage range of 5-30X. Unfortunately for your data, the very high coverage (300x) is much greater than the data set used to train the model used in dysgu. This might mean the model doesnt generalise very well to this dataset - the model might give meaningless results, or alternatively the best threshold for the probability metric might be far from the 0.45 default

**Comment by splaisan** [comment]
HI @kcleal,
Thanks for the detailed answer.
my dataset is the yeast dataset [SRR18210286](https://www.ncbi.nlm.nih.gov/sra/?term=SRR18210286) published recently by [Zhang et al](https://doi.org/10.1093/bib/bbac146) to compare assemblers and which constitutes a pretty nice data for subsampling or calling things at very high depth in yeast (my next project).
How do you suggest to test the effect of --thresholds in my case? (values closer to 1 or to 0 or both)
I am happy to test share the results back with you.

**Comment by kcleal** [comment]
I dont have any guidance for such high coverage data im afraid. It depends on what you are looking for in your sample - if your target SVs have low frequency (sequencing depth) in the sample then you want higher sensitivity (low prob values). However if they are clonal SVs (more likely from looking at the paper?) then higher prob values might work better. Additionally, for high coverage data, it might also be worth looking at the read-support as a metric to filter on, this is given as `SU` in the vcf file.

**Comment by splaisan** [comment]
Thanks, 
Yes I was planning to require at least 20 or 50 for SU as my genome is diploid and single sample and do post filtering on this.
I will see in comparison with sniffles what the recall is.
Best
