### ISSUE TITLE
GT value for missing data

### ISSUE THREAD

**Issue by linsson** [kcleal/dysgu#61]
Dear dysgu developers,

I am finding many `0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0` (FORMAT: `GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB`) in my results. I also have a `./.:.:33.5:1:0:1:0:0:0:0:6:1:1:0:0:42:-1:-1:-1:0.496.` What's the difference between GT=0 and GT=./. in dysgu? Is it expected to have GT=./. followed by some nonzero values?

**Comment by kcleal** [comment]
Hi @linsson,
The `./.` values end up in the output when there is not enough information to call a genotype. The `0` usually appears after you try and merge vcfs, 0 in this case means no SV or 0/0 genotype. What command did you run?

**Comment by kcleal** [comment]
Anything with `0` in genotype can be considered reference. However, dysgu does not fill out other information for sites with `0` genotype, so the COV values etc are not filled out. I guess some more information like COV could be added to the output when a `--sites` file is used, however the call would remain 0 for genotype.

**Comment by linsson** [comment]
Thank you your answer @kcleal !
