### ISSUE TITLE
no command as dysgu filter-normal

### ISSUE THREAD

**Issue by GManjiLab** [kcleal/dysgu#62]

**Comment by GManjiLab** [comment]
Hi

I tried to run dysgu filter-normal but got no such a command error. I installed via pip. Thank you!

**Comment by GManjiLab** [comment]
thanks: dysgu, version 1.3.16

**Comment by kcleal** [comment]
Ah, that is the problem! You will need to upgrade to the latest version to use filter-normal.

**Comment by GManjiLab** [comment]
i followed the installation instruction via pip. How can I upgrade to the latest version?

**Comment by kcleal** [comment]
I think with `pip install dysgu --upgrade`
