### ISSUE TITLE
what is SVLEN？

### ISSUE THREAD

**Issue by wenyuhaokikika** [kcleal/dysgu#63]
Thanks to dysgu, it's a really great tool.
I have a question during running:

for this
![image](https://github.com/kcleal/dysgu/assets/40107519/162ef87b-2fad-45f3-8e37-392fcb47501d)

As shown in the picture above, I think it means that the C at position 1028532 on chromosome 1 is deleted, but the SVLEN is 550 shown in INFO, why? Shouldn't it be 1?

**Comment by kcleal** [comment]
Hi @wenyuhaokikika, 

The start of the SV is at ``1028532`` on chr1, but the END is listed in the info column as ``END=1029082``. The ``C`` indicates that the reference base at the start position is a C. SVLEN is the difference between the start and END. Hope that makes sense.

**Comment by wenyuhaokikika** [comment]
Thank you so much for your quick reply, I think I get it
it means position 1028532-1029082(1028532+550) on chromosome 1 is deleted
The main thing that confuses me is that CONTIGA and CONTIGB do not match the genome, so I ignore these two fragments
