### ISSUE TITLE
ENH: support cram

### ISSUE THREAD

**Issue by brentp** [kcleal/dysgu#7]
currently, if a cram file is sent, then dysgu will try to use a fasta over the network according to the header (which fails in my case).
it would be faster to use:
```
result = hts_set_fai_filename(f_in, fasta);
...
```
after `sam_open`. This will work for bam as well (in that it will have no effect for bam files).

**Comment by kcleal** [comment]
Hi, thanks for raising this I will get that fixed

**Comment by brentp** [comment]
See my PR that fixes.

**Comment by brentp** [comment]
closed by #8
