### ISSUE TITLE
long reads default mapq lowered to 1: help text for dysgu call still says pacbio and nanopore mode has --mq 20

### ISSUE THREAD

**Issue by tbenavi1** [kcleal/dysgu#70]
Hello,

In version 1.6.0 I believe the default mapq for long reads was lowered to 1. However, the help text for dysgu call incorrectly says that --mq is set to 20.

Also, I was wondering for the reason for the change? Does this change improve sensitivity without getting too many false positives? Do you have a recommended value for mq? Thanks for any information.

**Comment by kcleal** [comment]
Hi @tbenavi1,
Thanks for pointing this out, I will get it changed. Changing to mq 1 resulted in a small improvement in sensitivity, especially for the CMRG benchmark.
