### ISSUE TITLE
Got an warning when Loading Model in "dysgu run"

### ISSUE THREAD

**Issue by LNGDingj** [kcleal/dysgu#73]
Hello @kcleal ,

Got the following warning when ran command "dysgu run" using [dysgu-run] Version: 1.6.1, can it be ignored? Thanks so much! 

 Loading Model: /opt/venv/lib/python3.11/site-packages/dysgu/dysgu_model.1.pkl.gz
/opt/venv/lib/python3.11/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 0.23.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to: https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

**Comment by kcleal** [comment]
Hi @LNGDingj, yes this warning can be ignored.
