### ISSUE TITLE
Process_KILLED

### ISSUE THREAD

**Issue by poddarharsh15** [kcleal/dysgu#86]
Hi @kcleal I am trying to run a bam files and after running for couple of minutes it gets KILLED, Could you please suggest some ideas I don't understand what's happening haven't seen dysgu doing this before :( 
Thanks in advance.
 

![Screenshot from 2024-03-21 16-45-09](https://github.com/kcleal/dysgu/assets/45700858/148effce-4077-4e98-8104-fd85ce2390af)

**Comment by kcleal** [comment]
Hi @poddarharsh15,
It looks like a lot of reads are being analysed - 363 million, is that expected? You could have a look at the bam file generated from the fetch stage in the working directory. If you index it with samtools, you will be able to inspect in in IGV or GW. Perhaps there are lots of adapter sequences, or soft-clipped reads in there? That could cause problems

**Comment by poddarharsh15** [comment]
I hope that's not the problem because adapter has been removed already and after that I removed also the duplicates using samtools. I will check it again last time when I ran Dysgu on the same samples without removing duplicates it didn't give me this problem.

**Comment by poddarharsh15** [comment]
Hi @kcleal I have checked other samples on which I have ran dysgu with similar reads count, please see examples below 
bwamem=502504302
dragen=503773618
minimap=502983985
![Screenshot from 2024-03-22 11-53-38](https://github.com/kcleal/dysgu/assets/45700858/0c586466-cdb7-4b7c-be96-ab01dc084039)

![Screenshot from 2024-03-22 11-54-09](https://github.com/kcleal/dysgu/assets/45700858/eeaa6b37-6f62-481d-81a9-ffe5fa6e689b)
Please let me know if you can provide some advice to make changes.
Thanks in advance.

**Comment by poddarharsh15** [comment]
I am investigating these two flowcells again I will get back to you ASAP. Thanks for the help appreciate it.

**Comment by poddarharsh15** [comment]
Seems like I have found the issue why this was happening because after removal of duplicates the properly mapped read % got extremely lower :( Please the images below for the reference many thanks again.
 
![Screenshot from 2024-03-22 13-25-54](https://github.com/kcleal/dysgu/assets/45700858/07ee7270-2ef8-4e53-bfc0-0d5bebbe253b)

**Comment by kcleal** [comment]
Ill close this for now
