### ISSUE TITLE
Paired-end reads calling sv

### ISSUE THREAD

**Issue by C-YONG** [kcleal/dysgu#88]
When I call call SVs, there was an error
dysgu run --sites combined_chang.vcf  genomic.fna wd /mnt/f/rmbam/4.sort.rmdup.bam > sample1.vcf
![image](https://github.com/kcleal/dysgu/assets/165139484/eb7cbf27-7d19-4807-827d-03ea84eeaf61)

**Comment by kcleal** [comment]
Hi @C-YONG,
Thanks for raising this. It is probably an issue with dysgu1.6.3. Would you be able to install v1.6.2? 
Could you tell me what aligner you are using?

**Comment by C-YONG** [comment]
Thank you for your answer, I use the 1.6.2 version, do I need to use the latest version？

**Comment by C-YONG** [comment]
I used the BWA alignment software for alignment, followed by using Picard to remove duplicates.

**Comment by kcleal** [comment]
Sorry, I've just had a look at the code that is causing this, I don't think either will solve the issue.

For some reason the name of the reference genome can't be encoded in ascii format. Are there any unusual characters in the reference genome name, the one provided on the command line? This is the problem line that is failing:

```
fasta_b = args["reference"].encode("ascii")
```

**Comment by kcleal** [comment]
Could you provide the full stderr output from the run? Thanks!

**Comment by C-YONG** [comment]
Thank you very much for your help, the cause of the error was unusual character in the name of the reference genome, we changed it and the programme works fine!
