### ISSUE TITLE
using short paired end split reads?

### ISSUE THREAD

**Issue by egnst** [kcleal/dysgu#91]
I'm studying a dataset where each sample has one known translocation, and I'm trying to detect if they have other SVs, as well. We performed paired-end short read targeted capture sequencing, so I have a high sequencing depth for several regions of interest. 

I aligned my experiment using BWA MEM. When I look at reads that align to the site of the known translocation, I can see that I have a lot of split reads that align to ~50bp on either side of the expected breakpoint. When I run Dysgu, it doesn't call the known translocation. In addition, for every SV that is called, SR=0, so I guess all of these split reads are not being utilized. What is the correct way to include split reads in short read PE analyses? 

I'm using dysgu v.1.6.3 and python 3.12.1. I've been troubleshooting the "dysgu run" parameters, most recently: 

dysgu run -p4 -x --keep-small --min-support 3 --metrics --max-cov -1 hg38.fa temp_dir bamfile.bam > vcffile.vcf

**Comment by kcleal** [comment]
Hi @egnst,
It's possible the supplementary reads are being ignored because they have low mapping quality, you can try setting the minimum map quality to zero `--mq 0`. If you could share a screenshot of the region using IGV or GW then I might be able to offer some more advice.

**Comment by kcleal** [comment]
Also it might be worth running samtools flagstats to check to see how many supplementary reads you have. Dysgu relies on the 2048 flag being set for split reads
