### ISSUE TITLE
Issue: Dysgu Module Integration and Empty VCF File Output

### ISSUE THREAD

**Issue by poddarharsh15** [kcleal/dysgu#93]
**Description**
I am currently working on adding `Dysgu` as a new module in nf-core/modules, with the aim of later incorporating it into the nf-core/sarek pipeline for Structural Variant (SV) calling.
(https://github.com/nf-core/sarek/tree/3.4.2)

**Issue Details**
The module has been created by me with assistance from other developers from nf-core/sarek @famosab. While `Dysgu` passes all the tests and works well within the module, it returns an empty VCF file (a text file) when run on the test data provided by the nf-core community. In theory, it should at least return an empty VCF file with a header, similar to other tools like `Manta` and `Tiddit` when run with the same data.

**Steps to Reproduce**
Create the Dysgu module in nf-core/modules.
Run Dysgu on the provided test data from the nf-core community.
Observe that the resulting VCF file is empty, lacking even the expected header.

**Expected Behavior**
The Dysgu module should produce a VCF file with a header, even if no variants are detected, similar to the behavior observed with `Manta` and `Tiddit`.

Test data files used for Dysgu (https://github.com/nf-core/test-datasets/tree/sarek3)
[input.zip](https://github.com/user-attachments/files/15986469/input.zip)

Output VCF files from `Manta` and `Tiddit` runs on the same test data
[sample1.manta.diploid_sv.vcf.gz](https://github.com/user-attachments/files/15986477/sample1.manta.diploid_sv.vcf.gz)
[sample1.tiddit.vcf.gz](https://github.com/user-attachments/files/15986489/sample1.tiddit.vcf.gz)

Could you please investigate this issue? I am tagging #sarek developers in this issue to help identify the problem. Your assistance is highly appreciated! @famosab

Thank you for your help.

**Comment by kcleal** [comment]
Thanks @poddarharsh15,
This should be no problem to add.

**Comment by poddarharsh15** [comment]
I am tagging this issue from yesterday, as you helped me in improving the command line. This will ensure everything is together if we need further information. [https://github.com/kcleal/dysgu/issues/92](url)
Thank you again :)

**Comment by kcleal** [comment]
Hi @poddarharsh15 ,
dysgu 1.6.4 is available on pypi. It should be on conda in a few days.

**Comment by poddarharsh15** [comment]
Thank you for the update, @kcleal. I will perform some test runs using the new versions and update you.

**Comment by poddarharsh15** [comment]
Hi @kcleal 
The tests were successfully passed, and I was able to create empty VCF files with headers. Thank you for the update again.
If you don't mind, could you please let me know how many days it will take for this version to be available on any conda channel?

**Comment by kcleal** [comment]
Hi @poddarharsh15,
Great. I will do some work on the build today - one of the dependencies is causing the build to fail at the moment. It might be fixed by the end of the day.

**Comment by kcleal** [comment]
Hi @poddarharsh15,
It should now be available on bioconda.

**Comment by poddarharsh15** [comment]
Thanks for the update, @kcleal I have successfully installed dysgu==1.6.4 package using bioconda, just one concern when i am running `dysgu --version` command it emits out `1.6.5`   Is that okay?

**Comment by kcleal** [comment]
My apologies, I forgot to edit the tags on the release. This might cause a bit of confusion, so will have to add a new release to fix. There will be no changes other than fixing the version issue. Thanks for reporting this.
